org: benny568
app: cloudca
service: cloudca

frameworkVersion: '2.66.2'

package:
  individually: True
  patterns:
    # Exclude everything first.
    - '!**/*'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  - ${file(./src/get_members_by_team/function.yml)}
  - ${file(./src/get_all_members/function.yml)}
  - ${file(./src/get_all_teams/function.yml)}
  - ${file(./src/get_team/function.yml)}
  - ${file(./src/get_news_stories/function.yml)}
  - ${file(./src/submit_news_story/function.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    noDeploy:
      - pytest
      - virtualenv
      - black
      - pre-commit
      - moto
    slim: true
    pythonBin: /usr/local/opt/python@3.8/bin/python3 # Installed using `brew install python@3.8` on MacOs

resources:
  Resources:
    - ${file(./src/cloudformation/news-table.yml)}
    - ${file(./src/cloudformation/team-table.yml)}
    - ${file(./src/cloudformation/members-table.yml)}
    - ${file(./src/cloudformation/cloudca-bucket.yml)}
