org: benny568
app: cloudca
service: cloudca

frameworkVersion: '2'

package:
  individually: True
  patterns:
    # Exclude everything first.
    - '!**/*'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  getMembersByTeam:
    name: getMembersByTeam
    handler: get_members_by_team/handler.get_members_by_team_handler
    module: src/get_members_by_team
    package:
      patterns:
        - src/get_members_by_team/**
        - src/common/**
        - src/__init__.py # needed to reference src as a package

  getAllMembers:
    name: getAllMembers
    handler: get_all_members/handler.get_all_members
    module: src/get_all_members
    package:
      patterns:
        - src/get_all_members/**
        - src/common/**
        - src/__init__.py # needed to reference src as a package

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: /usr/local/opt/python@3.8/bin/python3 # Installed using `brew install python@3.8`
