org: benny568
app: cloudca
service: cloudca

frameworkVersion: '2.68.0'

package:
  individually: True
  patterns:
    # Exclude everything first.
    - '!**/*'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  - ${file(./src/routes/member/add_member/function.yml)}
  - ${file(./src/routes/member/get_all_members/function.yml)}
  - ${file(./src/routes/member/get_members_by_team/function.yml)}
  - ${file(./src/routes/member/update_member/function.yml)}
  - ${file(./src/routes/news/delete_news_stories/function.yml)}
  - ${file(./src/routes/news/get_news_stories/function.yml)}
  - ${file(./src/routes/news/submit_news_story/function.yml)}
  - ${file(./src/routes/team/get_all_teams/function.yml)}
  - ${file(./src/routes/team/get_team/function.yml)}

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    noDeploy:
      - pytest
      - virtualenv
      - black
      - pre-commit
      - moto
      - coverage
      - pytest
    slim: true
    pythonBin: /usr/local/opt/python@3.9/bin/python3 # Installed using `brew install python@3.9` on MacOs

resources:
  Resources:
    newsTable: ${file(./src/cloudformation/news-table.yml)}
    teamTable: ${file(./src/cloudformation/team-table.yml)}
    membersTable: ${file(./src/cloudformation/members-table.yml)}
    cloudcaBucket: ${file(./src/cloudformation/cloudca-bucket.yml)}
