membersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Members
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

teamTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Teams
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

newsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: News-Stories
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
