name: Build and Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        python-version: ['3.9'] # Using python 3.9 for serverless framework

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.python-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run Build
      run: npm run build --if-present
    - name: Run Tests
      env:
        AWS_DEFAULT_REGION: "us-east-1"
      run: npm test
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy to AWS
      run: serverless deploy --verbose
    - name: Check for deprecations
      if: ${{ failure() }}
      run: serverless doctor