# This workflow will build the service and then deploy using the Serverless Framework.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: deploy
    needs: build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '16.14' ]
        python-version: [ '3.9' ] # Using python 3.9 for serverless framework

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}