# This workflow will build the service and then deploy using the Serverless Framework.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: deploy
    needs: build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.19' ]
        python-version: [ '3.9' ] # Using python 3.9 for serverless framework
        stages:
          stage: ['dev']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Install SLS Plugins and Deploy
        uses: serverless/github-action@v3.0.0
        with:
          args: -c "npm install --also=dev && npm list -g && npm list && serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
          entrypoint: /bin/bash

      - name: Run integration tests
        run: |
          make integration-tests