name: Build and Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        python-version: [3.9] # Using python 3.9 for serverless framework

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        python -m pip install pre-commit
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Run pre-commit hooks
#      run: |
#        pre-commit install
#        pre-commit run -a
#    - name: Run unit tests
#      env:
#        AWS_DEFAULT_REGION: "us-east-1"
#      run: |
#        make tests
    - name: Install NPM Packages
      run: npm ci
    - name: Print PATH
      run: echo $PATH
    - name: Copy Python3
      run: cp -Lr /opt/hostedtoolcache/Python/3.9.10/x64/bin/python3 /usr/local/opt/python@3.9/bin/python3
    - name: Print python bin
      run: ls -a usr/local/opt/python@3.9/bin/python3
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Deploy to AWS
      run: serverless deploy --verbose
#    - name: Check for deprecations
#      if: ${{ failure() }}
#      run: serverless doctor